global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'my-local-endpoint'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
  
  - job_name: 'metrics-publisher'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'metrics-publisher'
          environment: 'local'
  
  - job_name: 'api-test-runner'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'api-test-runner'
          environment: 'local'



